/**
 * Real SWAT outputRch data loader.
 *
 * The JSON is generated by `scripts/src/buildReachData.ts` from
 * `attached_assets/outputRch_*.xlsx` and bundled with the dashboard.
 *
 * Key concepts:
 *   - "global day index" = 0-based day from `startDate` across all years
 *     (range 0 … days-1, here 0 … 1094 for 2021-01-01 → 2023-12-31).
 *   - "year-relative day" = 0-based day-of-year (range 0 … 364) inside a
 *     single calendar year. Convert between them with `globalDayIdx(year, day)`.
 *   - reaches 10, 12, 20 have no model output and resolve to `null`. Render
 *     these as a neutral "no-data" grey, NOT zero.
 */

import rawData from "@/data/reachData.json";

export type ReachVar = "flow" | "n" | "p";

export interface ReachSeries {
  flow: number[]; // m³/s     length = days
  n:    number[]; // kg/day   length = days
  p:    number[]; // kg/day   length = days
}

export interface VarBounds {
  min: number;
  max: number;
  /** 99th-percentile value across all reaches × days. Used as the saturation
   *  point for log-scale color mapping so 1-in-100 storm days don't compress
   *  every other day into a single color band. */
  p99: number;
}

interface ReachDataset {
  startDate: string;       // "YYYY-MM-DD"
  endDate:   string;       // "YYYY-MM-DD"
  days:      number;       // total days (1095 for 2021-2023)
  years:     number[];     // [2021, 2022, 2023]
  reaches:   Record<string, ReachSeries | null>;
  bounds: {
    flow: VarBounds;
    n:    VarBounds;
    p:    VarBounds;
  };
}

const DATA = rawData as ReachDataset;

export const REACH_DATA_START_YEAR = DATA.years[0];
export const REACH_DATA_END_YEAR = DATA.years[DATA.years.length - 1];
export const REACH_DATA_YEARS = DATA.years as readonly number[];
export const REACH_DATA_DAYS = DATA.days;
export const REACH_DATA_BOUNDS = DATA.bounds;

/** Set of reach numbers that DO have non-zero model output. The complement
 *  (10, 12, 20 in our current dataset) renders as "No data". */
export const REACH_HAS_DATA: ReadonlySet<number> = new Set(
  Object.entries(DATA.reaches)
    .filter(([, v]) => v !== null)
    .map(([k]) => Number(k)),
);

/** Convert a (year, day-of-year) into a global day index into the dataset.
 *  Returns -1 if the year is outside the dataset. */
export function globalDayIdx(year: number, dayOfYear: number): number {
  const yIdx = DATA.years.indexOf(year);
  if (yIdx < 0) return -1;
  // All three years in our dataset are non-leap (365 days). If we ever ingest
  // a leap year we'll need a per-year offset table here.
  const offset = yIdx * 365;
  return offset + Math.max(0, Math.min(364, dayOfYear));
}

/** Real-data scalar for one reach on one day, or null if reach has no data
 *  or the year is outside the dataset. */
export function getReachDay(reachId: number, year: number, dayOfYear: number): { flow: number; n: number; p: number } | null {
  const series = DATA.reaches[String(reachId)];
  if (!series) return null;
  const idx = globalDayIdx(year, dayOfYear);
  if (idx < 0 || idx >= DATA.days) return null;
  return { flow: series.flow[idx], n: series.n[idx], p: series.p[idx] };
}

/** Full per-day series for a reach, or null if it has no model output. */
export function getReachSeries(reachId: number): ReachSeries | null {
  return DATA.reaches[String(reachId)] ?? null;
}

/** Annual mean per variable for a reach + year (used for normalization /
 *  scaling simulated detail grids by the day's real value). */
export function getReachAnnualMean(reachId: number, year: number, variable: ReachVar): number {
  const series = DATA.reaches[String(reachId)];
  if (!series) return 0;
  const yIdx = DATA.years.indexOf(year);
  if (yIdx < 0) return 0;
  const start = yIdx * 365;
  const end = start + 365;
  const arr = series[variable];
  let sum = 0;
  for (let i = start; i < end; i++) sum += arr[i];
  return sum / 365;
}

/**
 * Map a real reach value to the color stop fraction in [0, 1] using a
 * log scale anchored to the dataset's p99. Designed so that:
 *   - zero (or near-zero) values → 0 (lowest color)
 *   - typical "normal day" values → mid-range
 *   - p99 storm-day values        → ~0.85
 *   - max-ever storm spikes        → 1 (clamped, top color)
 */
export function reachValueToColorFraction(value: number, variable: ReachVar): number {
  const b = DATA.bounds[variable];
  if (value <= 0) return 0;
  // Log scale: log10(value + ε) mapped from [log10(ε), log10(p99 * 1.5)] → [0, 1].
  // Using p99 * 1.5 as the saturation point keeps "normal storm" days at
  // around 0.85–0.9 and reserves the top of the scale for true outlier spikes.
  const eps = Math.max(b.p99 * 1e-4, 1e-6);
  const lo = Math.log10(eps);
  const hi = Math.log10(b.p99 * 1.5);
  const lv = Math.log10(Math.max(eps, value));
  return Math.max(0, Math.min(1, (lv - lo) / (hi - lo)));
}
